package:
  name: pungi
  version: "0.2.0"

source:
  path: .

requirements:
  host:
    - python
    - pip
  run:
    - ruamel.yaml=0.17.*
    - psutil=5.9.*
    - snakemake=8.*

build:
  script: pip install .

about:
  home: https://github.com/rotary-genomics/pungi
  license: BSD 3
  license_file: LICENSE